version: '2'
services:
    php:
        build: ./php-fpm
        volumes:
            - ./individual-test:/var/www/individual-test
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./assets/test-gc-project.json:/var/www/test-gc-project.json
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /var/www/test-gc-project.json
        depends_on:
            - mysql
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./individual-test:/var/www/individual-test
            - ./nginx/individual-test.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    mysql:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: symf0ny
        ports:
            - "3333:3306"